import type { CheckDefinition } from './types.js';

/**
 * The check catalog is the single vocabulary of things BID can orchestrate.
 * Policies compose checks; providers execute them. Neither policies nor the
 * core engine know which provider will run a given check (ADR-005).
 *
 * `sourceLabel` is copied verbatim into evidence so that every result can
 * answer "where did this come from" without implying government endorsement.
 */
export const CHECK_CATALOG: CheckDefinition[] = [
  /* ---------------- Organization · identity ---------------- */
  {
    code: 'ORG_GST',
    label: 'GST registration',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Confirms the GST registration number resolves to the stated legal entity and is currently active.',
    sourceLabel: 'Authorized GST data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 180,
    unitCostPaise: 4900,
    slaHours: 1,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_PAN',
    label: 'PAN validation',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Validates the entity PAN and name match against the authorized verification source.',
    sourceLabel: 'Authorized PAN verification provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 2900,
    slaHours: 1,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_MCA',
    label: 'Company registry identity',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Resolves CIN/registry identity, incorporation date and current company status.',
    sourceLabel: 'Company registry data provider (MCA-derived)',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 180,
    unitCostPaise: 7900,
    slaHours: 2,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_DIRECTORS',
    label: 'Director / signatory check',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Lists current directors or authorized signatories associated with the registry record.',
    sourceLabel: 'Company registry data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 180,
    unitCostPaise: 5900,
    slaHours: 4,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: false,
  },
  {
    code: 'ORG_ADDRESS',
    label: 'Registered address',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'DOCUMENT',
    description: 'Confirms the operating/registered address against submitted documentation.',
    sourceLabel: 'Document verification provider',
    method: 'DOCUMENT',
    requiresConsent: false,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 3900,
    slaHours: 24,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_UDYAM',
    label: 'MSME / Udyam registration',
    category: 'IDENTITY',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Checks MSME/Udyam registration status where the entity claims one.',
    sourceLabel: 'MSME registration data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 2900,
    slaHours: 4,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },

  /* ---------------- Organization · financial ---------------- */
  {
    code: 'ORG_BANK',
    label: 'Bank account verification',
    category: 'FINANCIAL',
    subjectType: 'ORGANIZATION',
    capability: 'BANK',
    description: 'Penny-drop or equivalent validation that the bank account belongs to the entity.',
    sourceLabel: 'Bank verification provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 5900,
    slaHours: 2,
    evidenceVisibility: 'SENSITIVE',
    publicSummaryAllowed: false,
  },
  {
    code: 'ORG_TURNOVER',
    label: 'Declared turnover band',
    category: 'FINANCIAL',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Corroborates the declared turnover band against filings available to the provider.',
    sourceLabel: 'Financial filings data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 9900,
    slaHours: 24,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: false,
  },
  {
    code: 'ORG_FINANCIAL_HEALTH',
    label: 'Financial health indicators',
    category: 'FINANCIAL',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Summarizes filing regularity and financial stability indicators available to the provider.',
    sourceLabel: 'Financial data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 180,
    unitCostPaise: 14900,
    slaHours: 48,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: false,
  },

  /* ---------------- Organization · compliance ---------------- */
  {
    code: 'ORG_GST_FILING',
    label: 'GST filing regularity',
    category: 'COMPLIANCE',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Checks recent GST return filing regularity where data is available to the provider.',
    sourceLabel: 'Authorized GST data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 90,
    unitCostPaise: 4900,
    slaHours: 4,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_EPF',
    label: 'Statutory workforce compliance',
    category: 'COMPLIANCE',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Checks employer statutory registration/contribution signals where available.',
    sourceLabel: 'Statutory compliance data provider',
    method: 'API',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 180,
    unitCostPaise: 6900,
    slaHours: 24,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_CERTIFICATION',
    label: 'Certifications (ISO / quality)',
    category: 'COMPLIANCE',
    subjectType: 'ORGANIZATION',
    capability: 'DOCUMENT',
    description: 'Validates submitted certification documents and their validity window.',
    sourceLabel: 'Document verification provider',
    method: 'DOCUMENT',
    requiresConsent: false,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 4900,
    slaHours: 48,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_LICENCE',
    label: 'Sector licences',
    category: 'COMPLIANCE',
    subjectType: 'ORGANIZATION',
    capability: 'DOCUMENT',
    description: 'Validates sector-specific licences submitted by the entity (e.g. drug licence, labour licence).',
    sourceLabel: 'Document verification provider',
    method: 'DOCUMENT',
    requiresConsent: false,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 6900,
    slaHours: 48,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_INSURANCE',
    label: 'Insurance cover',
    category: 'COMPLIANCE',
    subjectType: 'ORGANIZATION',
    capability: 'DOCUMENT',
    description: 'Validates submitted liability / workmen compensation insurance cover and expiry.',
    sourceLabel: 'Document verification provider',
    method: 'DOCUMENT',
    requiresConsent: false,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 3900,
    slaHours: 48,
    evidenceVisibility: 'RELATIONSHIP_ONLY',
    publicSummaryAllowed: true,
  },

  /* ---------------- Organization · risk ---------------- */
  {
    code: 'ORG_SANCTIONS',
    label: 'Sanctions & watchlist screening',
    category: 'RISK',
    subjectType: 'ORGANIZATION',
    capability: 'RISK',
    description: 'Screens the entity and known signatories against sanctions and watchlist datasets held by the provider.',
    sourceLabel: 'Screening data provider (sanctions / watchlist datasets)',
    method: 'DATABASE',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 90,
    unitCostPaise: 7900,
    slaHours: 1,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: true,
  },
  {
    code: 'ORG_AML',
    label: 'AML / adverse media',
    category: 'RISK',
    subjectType: 'ORGANIZATION',
    capability: 'RISK',
    description: 'Adverse media and AML risk indicators from the provider dataset, with match confidence.',
    sourceLabel: 'Screening data provider (adverse media datasets)',
    method: 'DATABASE',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 90,
    unitCostPaise: 9900,
    slaHours: 4,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: false,
  },
  {
    code: 'ORG_LITIGATION',
    label: 'Litigation signals',
    category: 'RISK',
    subjectType: 'ORGANIZATION',
    capability: 'RISK',
    description: 'Publicly reported litigation signals associated with the entity, where the provider has coverage.',
    sourceLabel: 'Litigation data provider',
    method: 'DATABASE',
    requiresConsent: false,
    requiresDocument: false,
    defaultValidityDays: 90,
    unitCostPaise: 12900,
    slaHours: 48,
    evidenceVisibility: 'AUTHORIZED_ONLY',
    publicSummaryAllowed: false,
  },
  {
    code: 'ORG_UBO',
    label: 'Ownership / UBO structure',
    category: 'RISK',
    subjectType: 'ORGANIZATION',
    capability: 'KYB',
    description: 'Maps declared ownership structure and beneficial-owner declarations against registry data.',
    sourceLabel: 'Company registry + declaration review',
    method: 'MANUAL_REVIEW',
    requiresConsent: false,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 19900,
    slaHours: 72,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },

  /* ---------------- Person · BGV ---------------- */
  {
    code: 'PER_IDENTITY',
    label: 'Identity verification',
    category: 'IDENTITY',
    subjectType: 'PERSON',
    capability: 'IDENTITY',
    description: 'Verifies the person’s identity document details against the authorized verification source.',
    sourceLabel: 'Authorized identity verification provider',
    method: 'API',
    requiresConsent: true,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 4900,
    slaHours: 4,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_ADDRESS',
    label: 'Address verification',
    category: 'IDENTITY',
    subjectType: 'PERSON',
    capability: 'BGV',
    description: 'Confirms current/permanent address through digital or physical verification.',
    sourceLabel: 'Background verification provider',
    method: 'DOCUMENT',
    requiresConsent: true,
    requiresDocument: true,
    defaultValidityDays: 365,
    unitCostPaise: 24900,
    slaHours: 120,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_EDUCATION',
    label: 'Education verification',
    category: 'CREDENTIAL',
    subjectType: 'PERSON',
    capability: 'EDUCATION',
    description: 'Confirms the highest qualification with the issuing institution or its authorized agent.',
    sourceLabel: 'Education verification provider / issuing institution',
    method: 'MANUAL_REVIEW',
    requiresConsent: true,
    requiresDocument: true,
    defaultValidityDays: 1825,
    unitCostPaise: 29900,
    slaHours: 168,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_EMPLOYMENT',
    label: 'Employment verification',
    category: 'CREDENTIAL',
    subjectType: 'PERSON',
    capability: 'EMPLOYMENT',
    description: 'Confirms declared employment history with the previous employer or its authorized records.',
    sourceLabel: 'Employment verification provider / previous employer',
    method: 'MANUAL_REVIEW',
    requiresConsent: true,
    requiresDocument: false,
    defaultValidityDays: 730,
    unitCostPaise: 34900,
    slaHours: 168,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_PROF_CREDENTIAL',
    label: 'Professional credential',
    category: 'CREDENTIAL',
    subjectType: 'PERSON',
    capability: 'BGV',
    description: 'Validates professional registration or licence with the relevant professional body.',
    sourceLabel: 'Professional body / credential provider',
    method: 'MANUAL_REVIEW',
    requiresConsent: true,
    requiresDocument: true,
    defaultValidityDays: 730,
    unitCostPaise: 29900,
    slaHours: 168,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_DATABASE_CHECK',
    label: 'Permitted database screening',
    category: 'RISK',
    subjectType: 'PERSON',
    capability: 'BGV',
    description:
      'Screening against databases the provider is permitted to search for this purpose, subject to applicable law and consent scope.',
    sourceLabel: 'Background verification provider (permitted datasets)',
    method: 'DATABASE',
    requiresConsent: true,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 39900,
    slaHours: 240,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
  {
    code: 'PER_REFERENCE',
    label: 'Professional reference',
    category: 'PEOPLE',
    subjectType: 'PERSON',
    capability: 'BGV',
    description: 'Structured reference check with a nominated professional referee.',
    sourceLabel: 'Background verification provider (referee interview)',
    method: 'MANUAL_REVIEW',
    requiresConsent: true,
    requiresDocument: false,
    defaultValidityDays: 365,
    unitCostPaise: 19900,
    slaHours: 168,
    evidenceVisibility: 'RESTRICTED',
    publicSummaryAllowed: false,
  },
];

const BY_CODE = new Map(CHECK_CATALOG.map((c) => [c.code, c]));

export function getCheckDefinition(code: string): CheckDefinition | undefined {
  return BY_CODE.get(code);
}

export function requireCheckDefinition(code: string): CheckDefinition {
  const def = BY_CODE.get(code);
  if (!def) throw new Error(`Unknown check code: ${code}`);
  return def;
}

export function checksForSubject(subjectType: 'ORGANIZATION' | 'PERSON'): CheckDefinition[] {
  return CHECK_CATALOG.filter((c) => c.subjectType === subjectType);
}
