import type { Industry, MonitoringFrequency, RelationshipType, RiskLevel, SubjectType } from '../domain/enums.js';
import type { PolicyCheckRequirement, PolicyDocumentRequirement, PolicyThresholds } from '../domain/types.js';

/**
 * BID ships policy *templates*, not industry modules (ADR-004).
 * A hospital and a factory run the same engine; only the policy differs.
 */
export interface PolicyTemplate {
  key: string;
  name: string;
  description: string;
  subjectType: SubjectType;
  relationshipType: RelationshipType;
  industry: Industry;
  riskLevel: RiskLevel;
  requiredChecks: PolicyCheckRequirement[];
  optionalChecks: PolicyCheckRequirement[];
  documents: PolicyDocumentRequirement[];
  thresholds: PolicyThresholds;
  validityDays: number;
  reverificationDays: number;
  monitoringFrequency: MonitoringFrequency;
  approvalRule: 'AUTO' | 'MANUAL' | 'DUAL_CONTROL';
  requiresConsent: boolean;
}

const req = (checkCode: string, blocking = false, notes?: string): PolicyCheckRequirement => ({
  checkCode,
  required: true,
  blocking,
  notes,
});

const opt = (checkCode: string, notes?: string): PolicyCheckRequirement => ({
  checkCode,
  required: false,
  blocking: false,
  notes,
});

const doc = (
  code: string,
  label: string,
  required = true,
  visibility: PolicyDocumentRequirement['visibility'] = 'RELATIONSHIP_ONLY',
): PolicyDocumentRequirement => ({ code, label, required, visibility });

const THRESHOLDS: Record<RiskLevel, PolicyThresholds> = {
  LOW: { autoApproveScore: 65, reviewScore: 45, maxBlockingFailures: 1 },
  STANDARD: { autoApproveScore: 75, reviewScore: 55, maxBlockingFailures: 0 },
  HIGH: { autoApproveScore: 82, reviewScore: 65, maxBlockingFailures: 0 },
  CRITICAL: { autoApproveScore: 88, reviewScore: 72, maxBlockingFailures: 0 },
};

export const POLICY_TEMPLATES: PolicyTemplate[] = [
  {
    key: 'HR_CONSULTANCY_DD',
    name: 'HR Consultancy Due Diligence',
    description:
      'Due diligence for HR consultancies and staffing partners who will handle candidate data and place people into the requesting organization.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SERVICE_PROVIDER',
    industry: 'RECRUITMENT',
    riskLevel: 'HIGH',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA', true),
      req('ORG_ADDRESS'),
      req('ORG_EPF'),
      req('ORG_SANCTIONS', true),
      req('ORG_BANK'),
    ],
    optionalChecks: [opt('ORG_GST_FILING'), opt('ORG_AML'), opt('ORG_LITIGATION'), opt('ORG_CERTIFICATION')],
    documents: [
      doc('INCORPORATION', 'Certificate of incorporation'),
      doc('ADDRESS_PROOF', 'Registered address proof'),
      doc('DPA', 'Data processing commitment', false),
    ],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 330,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
  {
    key: 'STANDARD_SUPPLIER',
    name: 'Standard Supplier Policy',
    description: 'Baseline identity, compliance and screening checks for routine suppliers.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SUPPLIER',
    industry: 'GENERIC',
    riskLevel: 'STANDARD',
    requiredChecks: [req('ORG_GST', true), req('ORG_PAN', true), req('ORG_MCA'), req('ORG_SANCTIONS', true)],
    optionalChecks: [opt('ORG_BANK'), opt('ORG_ADDRESS'), opt('ORG_GST_FILING'), opt('ORG_UDYAM')],
    documents: [doc('ADDRESS_PROOF', 'Registered address proof', false)],
    thresholds: THRESHOLDS.STANDARD,
    validityDays: 365,
    reverificationDays: 335,
    monitoringFrequency: 'MONTHLY',
    approvalRule: 'AUTO',
    requiresConsent: false,
  },
  {
    key: 'CRITICAL_SUPPLIER',
    name: 'Critical Supplier Policy',
    description:
      'Deep due diligence for suppliers whose failure would interrupt production: identity, financial, compliance and risk, monitored quarterly.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SUPPLIER',
    industry: 'MANUFACTURING',
    riskLevel: 'CRITICAL',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA', true),
      req('ORG_ADDRESS'),
      req('ORG_BANK', true),
      req('ORG_TURNOVER'),
      req('ORG_CERTIFICATION'),
      req('ORG_SANCTIONS', true),
      req('ORG_AML', true),
      req('ORG_LITIGATION'),
    ],
    optionalChecks: [opt('ORG_FINANCIAL_HEALTH'), opt('ORG_UBO'), opt('ORG_INSURANCE'), opt('ORG_GST_FILING')],
    documents: [
      doc('INCORPORATION', 'Certificate of incorporation'),
      doc('ISO_CERT', 'Quality certification (ISO or equivalent)'),
      doc('BANK_LETTER', 'Bank account confirmation', true, 'SENSITIVE'),
      doc('FINANCIALS', 'Last two years financial statements', false, 'AUTHORIZED_ONLY'),
    ],
    thresholds: THRESHOLDS.CRITICAL,
    validityDays: 365,
    reverificationDays: 300,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'DUAL_CONTROL',
    requiresConsent: false,
  },
  {
    key: 'HEALTHCARE_VENDOR',
    name: 'Healthcare Vendor Policy',
    description:
      'Vendors supplying goods or services into clinical environments: licences, certifications and sanctions screening are blocking.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'VENDOR',
    industry: 'HEALTHCARE',
    riskLevel: 'HIGH',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA', true),
      req('ORG_LICENCE', true, 'Sector licence is blocking for clinical supply'),
      req('ORG_CERTIFICATION'),
      req('ORG_SANCTIONS', true),
      req('ORG_ADDRESS'),
    ],
    optionalChecks: [opt('ORG_INSURANCE'), opt('ORG_AML'), opt('ORG_LITIGATION'), opt('ORG_BANK')],
    documents: [doc('DRUG_LICENCE', 'Applicable sector licence'), doc('ISO_CERT', 'Quality certification', false)],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 300,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
  {
    key: 'CRITICAL_CONTRACTOR',
    name: 'Critical Contractor Policy',
    description:
      'Contractors deploying workforce on site: statutory workforce compliance and insurance cover are required alongside identity.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'CONTRACTOR',
    industry: 'CONSTRUCTION',
    riskLevel: 'CRITICAL',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA'),
      req('ORG_EPF', true),
      req('ORG_INSURANCE', true),
      req('ORG_LICENCE'),
      req('ORG_SANCTIONS', true),
      req('ORG_ADDRESS'),
    ],
    optionalChecks: [opt('ORG_LITIGATION'), opt('ORG_BANK'), opt('ORG_TURNOVER')],
    documents: [
      doc('LABOUR_LICENCE', 'Labour licence'),
      doc('INSURANCE', 'Workmen compensation insurance'),
      doc('SAFETY_POLICY', 'Site safety policy', false),
    ],
    thresholds: THRESHOLDS.CRITICAL,
    validityDays: 270,
    reverificationDays: 240,
    monitoringFrequency: 'MONTHLY',
    approvalRule: 'DUAL_CONTROL',
    requiresConsent: false,
  },
  {
    key: 'FLEET_CONTRACTOR',
    name: 'Fleet / Transport Contractor Policy',
    description: 'Transport contractors: entity identity, insurance, statutory compliance and screening.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'CONTRACTOR',
    industry: 'LOGISTICS',
    riskLevel: 'HIGH',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_INSURANCE', true),
      req('ORG_LICENCE'),
      req('ORG_SANCTIONS', true),
    ],
    optionalChecks: [opt('ORG_MCA'), opt('ORG_BANK'), opt('ORG_LITIGATION')],
    documents: [doc('TRANSPORT_LICENCE', 'Transport / permit documentation'), doc('INSURANCE', 'Fleet insurance')],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 330,
    monitoringFrequency: 'MONTHLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
  {
    key: 'DISTRIBUTOR',
    name: 'Distributor Onboarding Policy',
    description: 'Channel partners and distributors: identity, banking and financial standing.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'DISTRIBUTOR',
    industry: 'RETAIL',
    riskLevel: 'STANDARD',
    requiredChecks: [req('ORG_GST', true), req('ORG_PAN', true), req('ORG_BANK'), req('ORG_SANCTIONS', true)],
    optionalChecks: [opt('ORG_TURNOVER'), opt('ORG_MCA'), opt('ORG_FINANCIAL_HEALTH')],
    documents: [doc('BANK_LETTER', 'Bank account confirmation', true, 'SENSITIVE')],
    thresholds: THRESHOLDS.STANDARD,
    validityDays: 365,
    reverificationDays: 335,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'AUTO',
    requiresConsent: false,
  },
  {
    key: 'IT_VENDOR',
    name: 'IT / Software Vendor Policy',
    description: 'Software and IT service vendors with access to systems or data.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'VENDOR',
    industry: 'IT',
    riskLevel: 'HIGH',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA'),
      req('ORG_CERTIFICATION'),
      req('ORG_SANCTIONS', true),
    ],
    optionalChecks: [opt('ORG_AML'), opt('ORG_LITIGATION'), opt('ORG_FINANCIAL_HEALTH'), opt('ORG_INSURANCE')],
    documents: [doc('ISO_CERT', 'Security certification (ISO 27001 or equivalent)', false), doc('DPA', 'Data processing commitment', false)],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 330,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
  {
    key: 'CANDIDATE_BGV',
    name: 'Candidate BGV Policy',
    description:
      'Pre-employment background verification for candidates. Runs only with a recorded, in-scope consent from the candidate.',
    subjectType: 'PERSON',
    relationshipType: 'CANDIDATE',
    industry: 'GENERIC',
    riskLevel: 'STANDARD',
    requiredChecks: [req('PER_IDENTITY', true), req('PER_ADDRESS'), req('PER_EDUCATION'), req('PER_EMPLOYMENT', true)],
    optionalChecks: [opt('PER_DATABASE_CHECK'), opt('PER_REFERENCE'), opt('PER_PROF_CREDENTIAL')],
    documents: [doc('ID_DOC', 'Government identity document', true, 'RESTRICTED'), doc('DEGREE', 'Highest qualification certificate', true, 'RESTRICTED')],
    thresholds: THRESHOLDS.STANDARD,
    validityDays: 365,
    reverificationDays: 365,
    monitoringFrequency: 'EVENT_DRIVEN',
    approvalRule: 'MANUAL',
    requiresConsent: true,
  },
  {
    key: 'EMPLOYEE_BGV',
    name: 'Employee BGV Policy',
    description: 'Verification package for employees joining regulated or client-facing roles.',
    subjectType: 'PERSON',
    relationshipType: 'EMPLOYER',
    industry: 'IT',
    riskLevel: 'HIGH',
    requiredChecks: [
      req('PER_IDENTITY', true),
      req('PER_ADDRESS'),
      req('PER_EDUCATION'),
      req('PER_EMPLOYMENT', true),
      req('PER_DATABASE_CHECK'),
    ],
    optionalChecks: [opt('PER_REFERENCE'), opt('PER_PROF_CREDENTIAL')],
    documents: [doc('ID_DOC', 'Government identity document', true, 'RESTRICTED'), doc('DEGREE', 'Highest qualification certificate', true, 'RESTRICTED')],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 365,
    monitoringFrequency: 'EVENT_DRIVEN',
    approvalRule: 'MANUAL',
    requiresConsent: true,
  },
  {
    key: 'EDUCATION_STAFF',
    name: 'Education Staff & Vendor Policy',
    description: 'Staff and vendors operating on education campuses.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SERVICE_PROVIDER',
    industry: 'EDUCATION',
    riskLevel: 'HIGH',
    requiredChecks: [req('ORG_GST', true), req('ORG_PAN', true), req('ORG_EPF'), req('ORG_SANCTIONS', true), req('ORG_ADDRESS')],
    optionalChecks: [opt('ORG_INSURANCE'), opt('ORG_LITIGATION'), opt('ORG_CERTIFICATION')],
    documents: [doc('ADDRESS_PROOF', 'Registered address proof')],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 330,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
  {
    key: 'HOSPITALITY_SUPPLIER',
    name: 'Hospitality Supplier Policy',
    description: 'Food, facilities and hospitality suppliers where licences and insurance matter.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SUPPLIER',
    industry: 'HOSPITALITY',
    riskLevel: 'STANDARD',
    requiredChecks: [req('ORG_GST', true), req('ORG_PAN', true), req('ORG_LICENCE'), req('ORG_SANCTIONS', true)],
    optionalChecks: [opt('ORG_INSURANCE'), opt('ORG_CERTIFICATION'), opt('ORG_ADDRESS')],
    documents: [doc('FOOD_LICENCE', 'Applicable sector licence', false)],
    thresholds: THRESHOLDS.STANDARD,
    validityDays: 365,
    reverificationDays: 335,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'AUTO',
    requiresConsent: false,
  },
  {
    key: 'PHARMA_SUPPLIER',
    name: 'Pharma Supplier Policy',
    description: 'Pharmaceutical supply chain partners with licence, quality and screening requirements.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'SUPPLIER',
    industry: 'PHARMA',
    riskLevel: 'CRITICAL',
    requiredChecks: [
      req('ORG_GST', true),
      req('ORG_PAN', true),
      req('ORG_MCA', true),
      req('ORG_LICENCE', true),
      req('ORG_CERTIFICATION', true),
      req('ORG_SANCTIONS', true),
      req('ORG_AML', true),
    ],
    optionalChecks: [opt('ORG_UBO'), opt('ORG_LITIGATION'), opt('ORG_FINANCIAL_HEALTH')],
    documents: [doc('DRUG_LICENCE', 'Drug / manufacturing licence'), doc('GMP', 'GMP or equivalent quality evidence', false)],
    thresholds: THRESHOLDS.CRITICAL,
    validityDays: 270,
    reverificationDays: 240,
    monitoringFrequency: 'MONTHLY',
    approvalRule: 'DUAL_CONTROL',
    requiresConsent: false,
  },
  {
    key: 'BPO_PARTNER',
    name: 'BPO / KPO Partner Policy',
    description: 'Outsourcing partners processing customer data on behalf of the requester.',
    subjectType: 'ORGANIZATION',
    relationshipType: 'PARTNER',
    industry: 'BPO_KPO',
    riskLevel: 'HIGH',
    requiredChecks: [req('ORG_GST', true), req('ORG_PAN', true), req('ORG_MCA'), req('ORG_EPF'), req('ORG_SANCTIONS', true)],
    optionalChecks: [opt('ORG_CERTIFICATION'), opt('ORG_AML'), opt('ORG_FINANCIAL_HEALTH')],
    documents: [doc('DPA', 'Data processing commitment'), doc('ISO_CERT', 'Security certification', false)],
    thresholds: THRESHOLDS.HIGH,
    validityDays: 365,
    reverificationDays: 330,
    monitoringFrequency: 'QUARTERLY',
    approvalRule: 'MANUAL',
    requiresConsent: false,
  },
];

export function getPolicyTemplate(key: string): PolicyTemplate | undefined {
  return POLICY_TEMPLATES.find((t) => t.key === key);
}
